server:
  port: 8080

spring:
  application:
    name: cs-registry

# 配置 Eureka Server 注冊中心
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8080/eureka/