server:
  port: 8082 # 端口

spring:
  application:
    name: cs-oauth2-server # 應用名
  # 數據庫
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
    url: jdbc:mysql://192.168.5.135:30306/dinerDB?serverTimezone=Asia/Taipei&characterEncoding=utf8&useUnicode=true&useSSL=false
  # Redis
  redis:
    port: 6379
    host: 192.168.5.139
    timeout: 3000
    database: 1
    password: 123456
  # swagger
  swagger:
    base-package: com.dc.oauth2
    title: 美食社交食客API規格文件

# Oauth2
client:
  oauth2:
    client-id: appId # 客戶端標識 ID
    secret: 123456 # 客戶端安全碼
    # 授權類型
    grant_types:
      - password
      - refresh_token
    # token 有效時間，單位秒
    token-validity-time: 3600
    refresh-token-validity-time: 3600
    # 客戶端訪問範圍
    scopes:
      - api
      - all

# 配置 Eureka Server 注冊中心
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

# Mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true # 開啟駝峰映射

# 指標監控健康檢查
management:
  endpoints:
    web:
      exposure:
        include: "*" # 暴露的端點
