server:
  port: 800

spring:
  application:
    name: cs-gateway
  cloud:
    config:
      discovery:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true #開啟配置註冊中心進行路由功能
          lower-case-service-id: true #將服務名稱轉小寫
      routes:
        - id: cs-diners
          uri: lb://cs-diners
          predicates:
            - Path=/diners/**
          filters:
            - StripPrefix=1

        - id: cs-oauth2-server
          uri: lb://cs-oauth2-server
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        - id: cs-seckill
          uri: lb://cs-seckill
          predicates:
            - Path=/seckill/**
          filters:
            - StripPrefix=1

        - id: cs-follow
          uri: lb://cs-follow
          predicates:
            - Path=/follow/**
          filters:
            - StripPrefix=1

        - id: cs-feeds
          uri: lb://cs-feeds
          predicates:
            - Path=/feeds/**
          filters:
            - StripPrefix=1

        - id: cs-points
          uri: lb://cs-points
          predicates:
            - Path=/points/**
          filters:
            - StripPrefix=1

        - id: cs-restaurants
          uri: lb://cs-restaurants
          predicates:
            - Path=/restaurants/**
          filters:
            - StripPrefix=1

secure:
  ignore:
    urls: # 配置白名單路徑
      - /actuator/**
      - /auth/oauth/**
      - /diners/signin
      - /diners/send
      - /diners/checkPhone
      - /diners/register
      - /seckill/add
      - /restaurants/**

# 配置 Eureka Server 注冊中心
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/